name: wtf_app
description: Free Food Tracker - UMass
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Google Sign-In for authentication
  google_sign_in: ^6.1.5
  
  # State management
  provider: ^6.1.1
  
  # Secure storage for user data
  flutter_secure_storage: ^9.0.0

  # Google Maps requester.
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

  add_2_calendar: ^3.0.1
  url_launcher: ^6.2.2
  map_launcher: ^3.0.1

  share_plus: ^7.2.2
  flutter_contacts: ^1.1.7+1
  flutter_social_button: ^1.1.6+1
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true